# CAMERA SETTINGS:
CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
TARGET_FPS = 60


# MEDIA PIPELINE POSE:
MP_MIN_DETECTION_CONFIDENCE = 0.7
MP_MIN_TRACKING_CONFIDENCE = 0.7
MP_MODEL_COMPLEXITY = 1  # 0:LITE, 1:FULL, 2:HEAVY


# GESTURE CLASSIFIER:
GESTURE_LABELS = [
    "idle",
    "charging",
    "firing",
    "kamehameha",
    "spirit_bomb",
    "teleport",
    "power_up",
    "block",
]
MODEL_PATH = "models/gesture_classifier.pkl"
CONFIDENCE_THRESHOLD = 0.65  # MIN PROBABILITY TO ACCEPT A PREDICTION


# STATE MACHINE:
CHARGE_HOLD_FRAMES = 15  # FRAMES GESTURE MUST BE HOLD TO TRIGGER
COOLDOWN_FRAMES = 30  # fRAMES BETWEEN FIRING


# FEATURE EXTRACTION;
USE_ANGLES = True
USE_velocity = True
smoothing_window = 5

# effects:
PARTICLE_COUNT = 60
AURA_COLOR_CHARGING = (255, 200, 50)  # GOLD COLOR
AURA_COLOR_CHARGING = (50, 150, 255)  # BLUE COLOR
AURA_COLOR_CHARGING = (100, 200, 255)  # CYAN-WHITE COLOR
BLAST_SPEED = 18


# HUD OVERLAY
HUD_COLOR_PRIMARY = (255, 215, 0)  # GOLD
HUD_COLOR_SECONDARY = (30, 144, 255)  # BLUE
HUD_ALPHA = 0.75
ENERGY_MAX = 100
ENERGY_REGEN_RATE = 0.4
ENERGY_COST_FIRE = 30
ENERGY_COST_KAMEHAMEHA = 60


# PERFORMANCE:
SHOW_FPS = True
SHOW_LATENCY = True
PREF_LOG_INTERVAL = 60

# DATASET COLLECTION:
DATASET_DIR = "data/gesture_dataset"
FRAME_PER_GESTURE = 200  # PER LABEL SAMPLE COLLECTED
